spring:
  cloud:
    function:
      definition: producer;consumer;processor #uses producer, consumer, and processor
    stream:
      bindings:
        consumer-in-0:
          destination: output-topic
          group: consumer-group
        processor-in-0:
          destination: input-topic
          group: processor-group
        processor-out-0:
          destination: output-topic
        producer-out-0:
          destination: input-topic
# producer produces something
# processor consumers it through input topic
# processor produces
#consumer then consumes it