spring:
  cloud:
    function:
      definition: consumer #uses only function and ignores the consumer defined
    stream:
      bindings:
        consumer-in-0:
          destination: input-topic
          group: some-group
          consumer:
            use-native-decoding: true #optional
        producer-out-0:
          producer:
            use-native-encoding: true #compulsory
      kafka:
        binder:
          consumer-properties:
            "value.deserializer": org.springframework.kafka.support.serializer.JsonDeserializer
            "auto.offset.reset": "earliest"
            "group.instance.id": "1"
            "spring.json.trusted.packages": "*"