spring:
  cloud:
    function:
      definition: producer;consumer;processor #uses producer, consumer, and processor
    stream:
      bindings:
        consumer-in-0:
          destination: input-topic
          group: some-group
        producer-out-0:
          destination: input-topic
      kafka:
        binder:
          producer-properties:
            "key.serializer": org.apache.kafka.common.serialization.StringSerializer
          consumer-properties:
            "key.deserializer": org.apache.kafka.common.serialization.StringDeserializer
            "auto.offset.reset": "earliest"
# producer produces something
# processor consumers it through input topic
# processor produces
#consumer then consumes it