spring:
  cloud:
    function:
      definition: producer;consumer #uses only function and ignores the consumer defined
    stream:
      bindings:
        consumer-in-0:
          destination: input-topic
          group: some-group
        producer-out-0:
          destination: input-topic
      kafka:
        bindings:
          producer-out-0:
            producer:
              configuration:
                "acks": "-1"
